In [51]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [52]:
df=pd.read_csv("Visadataset.csv")

In [53]:
df.head()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified

In [54]:
df.columns

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

#check the null value

In [5]:
feature_with_na=[feature for feature in df.columns if df[feature].isnull().sum()>1]

In [6]:
feature_with_na

[]

In [7]:
#no null values

In [8]:
df.duplicated().sum()

np.int64(0)

In [55]:
df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [56]:
ohec=["full_time_position","continent","unit_of_wage","region_of_employment","has_job_experience","requires_job_training"]
orec=["education_of_employee"]
scc=["prevailing_wage","no_of_employees"]

In [57]:
df.drop('case_id',inplace=True,axis=1)

In [58]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,StandardScaler,OrdinalEncoder,PowerTransformer

In [59]:
from math import remainder
from types import SimpleNamespace
transformer=ColumnTransformer(transformers=[
    ("OneHotencoder",OneHotEncoder(),ohec),
    ("ordinalencoder",OrdinalEncoder(),orec)

])

In [60]:
from sklearn.pipeline import Pipeline
pipeline=Pipeline(steps=[
    ("transformer",transformer),
    ("classifier",DecisionTreeClassifier())
])

In [61]:
x=df.drop('case_status',axis=1)
y=df['case_status']

In [62]:
y=np.where(y=='Denied',0,1)

In [63]:
from sklearn.model_selection import train_test_split

In [64]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [65]:
x_train.shape,x_test.shape

((20384, 10), (5096, 10))

In [66]:
from sklearn.tree import DecisionTreeClassifier

In [67]:
pipeline.fit(x_train,y_train)

Pipeline(steps=[('transformer',
                 ColumnTransformer(transformers=[('OneHotencoder',
                                                  OneHotEncoder(),
                                                  ['full_time_position',
                                                   'continent', 'unit_of_wage',
                                                   'region_of_employment',
                                                   'has_job_experience',
                                                   'requires_job_training']),
                                                 ('ordinalencoder',
                                                  OrdinalEncoder(),
                                                  ['education_of_employee'])])),
                ('classifier', DecisionTreeClassifier())])

In [69]:
y_train_pred=pipeline.predict(x_train)
y_test_pred=pipeline.predict(x_test)

In [70]:
y_train_pred

array([0, 1, 0, ..., 1, 1, 1])

In [71]:
y_train

array([0, 0, 1, ..., 1, 1, 1])

In [72]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,y_test_pred)
print(accuracy)

0.7533359497645212

In [74]:
accuracy=accuracy_score(y_train,y_train_pred)
print(accuracy)

0.7626079277864992

In [75]:
import pickle

pickle_model_path="model.pkl"
with open(pickle_model_path,'wb') as f:
    pickle.dump(pipeline,f)